var namespacetdc =
[
    [ "ds", "namespacetdc_1_1ds.html", "namespacetdc_1_1ds" ],
    [ "esp", "namespacetdc_1_1esp.html", "namespacetdc_1_1esp" ],
    [ "int_vector", "namespacetdc_1_1int__vector.html", "namespacetdc_1_1int__vector" ],
    [ "io", "namespacetdc_1_1io.html", "namespacetdc_1_1io" ],
    [ "json", "namespacetdc_1_1json.html", "namespacetdc_1_1json" ],
    [ "lcpcomp", "namespacetdc_1_1lcpcomp.html", "namespacetdc_1_1lcpcomp" ],
    [ "lfs", "namespacetdc_1_1lfs.html", "namespacetdc_1_1lfs" ],
    [ "lz78", "namespacetdc_1_1lz78.html", "namespacetdc_1_1lz78" ],
    [ "lz78u", "namespacetdc_1_1lz78u.html", "namespacetdc_1_1lz78u" ],
    [ "lzss", "namespacetdc_1_1lzss.html", "namespacetdc_1_1lzss" ],
    [ "test", "namespacetdc_1_1test.html", "namespacetdc_1_1test" ],
    [ "_DoubleHashingProber", "structtdc_1_1___double_hashing_prober.html", null ],
    [ "_VignaHasher", "structtdc_1_1___vigna_hasher.html", "structtdc_1_1___vigna_hasher" ],
    [ "Algorithm", "classtdc_1_1_algorithm.html", "classtdc_1_1_algorithm" ],
    [ "AlgorithmValue", "classtdc_1_1_algorithm_value.html", "classtdc_1_1_algorithm_value" ],
    [ "ArithmeticCoder", "classtdc_1_1_arithmetic_coder.html", "classtdc_1_1_arithmetic_coder" ],
    [ "ArrayDS", "classtdc_1_1_array_d_s.html", "classtdc_1_1_array_d_s" ],
    [ "ArrayMaxHeap", "classtdc_1_1_array_max_heap.html", "classtdc_1_1_array_max_heap" ],
    [ "ASCIICoder", "classtdc_1_1_a_s_c_i_i_coder.html", "classtdc_1_1_a_s_c_i_i_coder" ],
    [ "BinarySuffixTree", "classtdc_1_1_binary_suffix_tree.html", "classtdc_1_1_binary_suffix_tree" ],
    [ "BitCoder", "classtdc_1_1_bit_coder.html", "classtdc_1_1_bit_coder" ],
    [ "Bucket", "classtdc_1_1_bucket.html", "classtdc_1_1_bucket" ],
    [ "BucketElem", "classtdc_1_1_bucket_elem.html", "classtdc_1_1_bucket_elem" ],
    [ "Builder", "classtdc_1_1_builder.html", "classtdc_1_1_builder" ],
    [ "BWTCompressor", "classtdc_1_1_b_w_t_compressor.html", "classtdc_1_1_b_w_t_compressor" ],
    [ "ChainCompressor", "classtdc_1_1_chain_compressor.html", "classtdc_1_1_chain_compressor" ],
    [ "compact_hash", "classtdc_1_1compact__hash.html", "classtdc_1_1compact__hash" ],
    [ "CompressedLCP", "classtdc_1_1_compressed_l_c_p.html", "classtdc_1_1_compressed_l_c_p" ],
    [ "Compressor", "classtdc_1_1_compressor.html", "classtdc_1_1_compressor" ],
    [ "ConstGenericView", "classtdc_1_1_const_generic_view.html", "classtdc_1_1_const_generic_view" ],
    [ "ConstGenericView< uliteral_t >", "classtdc_1_1_const_generic_view_3_01uliteral__t_01_4.html", "classtdc_1_1_const_generic_view_3_01uliteral__t_01_4" ],
    [ "ConstIntegerBaseCombiner", "classtdc_1_1_const_integer_base_combiner.html", null ],
    [ "ConstIntegerBaseCombiner< T >", "classtdc_1_1_const_integer_base_combiner_3_01_t_01_4.html", null ],
    [ "ConstIntegerBaseCombiner< T, Ts... >", "classtdc_1_1_const_integer_base_combiner_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
    [ "ConstIntegerBaseTrait", "structtdc_1_1_const_integer_base_trait.html", [
      [ "type >", "structtdc_1_1_const_integer_base_trait_1_1type_01_4.html", "structtdc_1_1_const_integer_base_trait_1_1type_01_4" ]
    ] ],
    [ "ConstIntegerBaseTrait< bool >", "structtdc_1_1_const_integer_base_trait_3_01bool_01_4.html", "structtdc_1_1_const_integer_base_trait_3_01bool_01_4" ],
    [ "ConstIntegerBaseWith32", "classtdc_1_1_const_integer_base_with32.html", "classtdc_1_1_const_integer_base_with32" ],
    [ "ConstIntegerBaseWith64", "classtdc_1_1_const_integer_base_with64.html", "classtdc_1_1_const_integer_base_with64" ],
    [ "ConstIntegerBaseWithSelf", "classtdc_1_1_const_integer_base_with_self.html", "classtdc_1_1_const_integer_base_with_self" ],
    [ "Counter", "classtdc_1_1_counter.html", "classtdc_1_1_counter" ],
    [ "Decoder", "classtdc_1_1_decoder.html", "classtdc_1_1_decoder" ],
    [ "DoubleHashingProber", "classtdc_1_1_double_hashing_prober.html", "classtdc_1_1_double_hashing_prober" ],
    [ "dynamic_t", "classtdc_1_1dynamic__t.html", null ],
    [ "EliasDeltaCoder", "classtdc_1_1_elias_delta_coder.html", "classtdc_1_1_elias_delta_coder" ],
    [ "EliasGammaCoder", "classtdc_1_1_elias_gamma_coder.html", "classtdc_1_1_elias_gamma_coder" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_const_integer_base_trait_3_01uint__impl__t_3_01_n_01_4_00_01typename_01std_1_1enabd83b4faccb504945e50ffb316c814d1d.html", "structtdc_1_1_const_integer_base_trait_3_01uint__impl__t_3_01_n_01_4_00_01typename_01std_1_1enabd83b4faccb504945e50ffb316c814d1d" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_integer_base_trait_3_01uint__impl__t_3_01_n_01_4_00_01typename_01std_1_1enable__if7b932aef18cc061bf82ebd67f955ecb2.html", "structtdc_1_1_integer_base_trait_3_01uint__impl__t_3_01_n_01_4_00_01typename_01std_1_1enable__if7b932aef18cc061bf82ebd67f955ecb2" ],
    [ "Encoder", "classtdc_1_1_encoder.html", "classtdc_1_1_encoder" ],
    [ "Env", "classtdc_1_1_env.html", "classtdc_1_1_env" ],
    [ "EnvRoot", "classtdc_1_1_env_root.html", "classtdc_1_1_env_root" ],
    [ "EspCompressor", "classtdc_1_1_esp_compressor.html", "classtdc_1_1_esp_compressor" ],
    [ "FibonacciGenerator", "classtdc_1_1_fibonacci_generator.html", "classtdc_1_1_fibonacci_generator" ],
    [ "FixedRange", "classtdc_1_1_fixed_range.html", "classtdc_1_1_fixed_range" ],
    [ "GaussProber", "structtdc_1_1_gauss_prober.html", "structtdc_1_1_gauss_prober" ],
    [ "Generator", "classtdc_1_1_generator.html", "classtdc_1_1_generator" ],
    [ "GenericView", "classtdc_1_1_generic_view.html", "classtdc_1_1_generic_view" ],
    [ "GenericViewBase", "classtdc_1_1_generic_view_base.html", "classtdc_1_1_generic_view_base" ],
    [ "HashMap", "classtdc_1_1_hash_map.html", "classtdc_1_1_hash_map" ],
    [ "HuffmanCoder", "classtdc_1_1_huffman_coder.html", "classtdc_1_1_huffman_coder" ],
    [ "IntegerBaseCombiner", "classtdc_1_1_integer_base_combiner.html", null ],
    [ "IntegerBaseCombiner< T >", "classtdc_1_1_integer_base_combiner_3_01_t_01_4.html", null ],
    [ "IntegerBaseCombiner< T, Ts... >", "classtdc_1_1_integer_base_combiner_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
    [ "IntegerBaseTrait", "structtdc_1_1_integer_base_trait.html", [
      [ "type >", "structtdc_1_1_integer_base_trait_1_1type_01_4.html", "structtdc_1_1_integer_base_trait_1_1type_01_4" ]
    ] ],
    [ "IntegerBaseTrait< bool >", "structtdc_1_1_integer_base_trait_3_01bool_01_4.html", "structtdc_1_1_integer_base_trait_3_01bool_01_4" ],
    [ "IntegerBaseWith32", "classtdc_1_1_integer_base_with32.html", "classtdc_1_1_integer_base_with32" ],
    [ "IntegerBaseWith64", "classtdc_1_1_integer_base_with64.html", "classtdc_1_1_integer_base_with64" ],
    [ "IntegerBaseWithSelf", "classtdc_1_1_integer_base_with_self.html", "classtdc_1_1_integer_base_with_self" ],
    [ "ISAFromSA", "classtdc_1_1_i_s_a_from_s_a.html", "classtdc_1_1_i_s_a_from_s_a" ],
    [ "KarpRabinHash", "classtdc_1_1_karp_rabin_hash.html", "classtdc_1_1_karp_rabin_hash" ],
    [ "KnuthHasher", "structtdc_1_1_knuth_hasher.html", "structtdc_1_1_knuth_hasher" ],
    [ "LCPCompressor", "classtdc_1_1_l_c_p_compressor.html", "classtdc_1_1_l_c_p_compressor" ],
    [ "LCPForwardIterator", "classtdc_1_1_l_c_p_forward_iterator.html", "classtdc_1_1_l_c_p_forward_iterator" ],
    [ "LCPFromPLCP", "classtdc_1_1_l_c_p_from_p_l_c_p.html", "classtdc_1_1_l_c_p_from_p_l_c_p" ],
    [ "LCPSada", "classtdc_1_1_l_c_p_sada.html", "classtdc_1_1_l_c_p_sada" ],
    [ "LengthRange", "classtdc_1_1_length_range.html", "classtdc_1_1_length_range" ],
    [ "LinearProber", "structtdc_1_1_linear_prober.html", "structtdc_1_1_linear_prober" ],
    [ "Literal", "structtdc_1_1_literal.html", "structtdc_1_1_literal" ],
    [ "LiteralEncoder", "classtdc_1_1_literal_encoder.html", "classtdc_1_1_literal_encoder" ],
    [ "LiteralIterator", "classtdc_1_1_literal_iterator.html", "classtdc_1_1_literal_iterator" ],
    [ "LiteralRange", "classtdc_1_1_literal_range.html", "classtdc_1_1_literal_range" ],
    [ "LZ78Compressor", "classtdc_1_1_l_z78_compressor.html", "classtdc_1_1_l_z78_compressor" ],
    [ "LZ78UCompressor", "classtdc_1_1_l_z78_u_compressor.html", "classtdc_1_1_l_z78_u_compressor" ],
    [ "LZSSLCPCompressor", "classtdc_1_1_l_z_s_s_l_c_p_compressor.html", "classtdc_1_1_l_z_s_s_l_c_p_compressor" ],
    [ "LZSSSlidingWindowCompressor", "classtdc_1_1_l_z_s_s_sliding_window_compressor.html", "classtdc_1_1_l_z_s_s_sliding_window_compressor" ],
    [ "LZWCompressor", "classtdc_1_1_l_z_w_compressor.html", "classtdc_1_1_l_z_w_compressor" ],
    [ "Meta", "classtdc_1_1_meta.html", "classtdc_1_1_meta" ],
    [ "MinDistributedRange", "classtdc_1_1_min_distributed_range.html", "classtdc_1_1_min_distributed_range" ],
    [ "MixHasher", "structtdc_1_1_mix_hasher.html", "structtdc_1_1_mix_hasher" ],
    [ "MoveGuard", "classtdc_1_1_move_guard.html", "classtdc_1_1_move_guard" ],
    [ "msbf", "structtdc_1_1msbf.html", null ],
    [ "msbf< uint16_t >", "structtdc_1_1msbf_3_01uint16__t_01_4.html", null ],
    [ "msbf< uint32_t >", "structtdc_1_1msbf_3_01uint32__t_01_4.html", null ],
    [ "msbf< uint64_t >", "structtdc_1_1msbf_3_01uint64__t_01_4.html", null ],
    [ "msbf< uint8_t >", "structtdc_1_1msbf_3_01uint8__t_01_4.html", null ],
    [ "MTFCompressor", "classtdc_1_1_m_t_f_compressor.html", "classtdc_1_1_m_t_f_compressor" ],
    [ "NaivST", "classtdc_1_1_naiv_s_t.html", "classtdc_1_1_naiv_s_t" ],
    [ "NoLiterals", "classtdc_1_1_no_literals.html", null ],
    [ "NoopCompressor", "classtdc_1_1_noop_compressor.html", "classtdc_1_1_noop_compressor" ],
    [ "NoopHasher", "structtdc_1_1_noop_hasher.html", "structtdc_1_1_noop_hasher" ],
    [ "OptionValue", "classtdc_1_1_option_value.html", "classtdc_1_1_option_value" ],
    [ "PhiFromSA", "classtdc_1_1_phi_from_s_a.html", "classtdc_1_1_phi_from_s_a" ],
    [ "PLCPFromPhi", "classtdc_1_1_p_l_c_p_from_phi.html", "classtdc_1_1_p_l_c_p_from_phi" ],
    [ "QuadraticProber", "structtdc_1_1_quadratic_prober.html", "structtdc_1_1_quadratic_prober" ],
    [ "RandomUniformGenerator", "classtdc_1_1_random_uniform_generator.html", "classtdc_1_1_random_uniform_generator" ],
    [ "Range", "classtdc_1_1_range.html", "classtdc_1_1_range" ],
    [ "Rank", "classtdc_1_1_rank.html", "classtdc_1_1_rank" ],
    [ "Registry", "classtdc_1_1_registry.html", "classtdc_1_1_registry" ],
    [ "RePairCompressor", "classtdc_1_1_re_pair_compressor.html", "classtdc_1_1_re_pair_compressor" ],
    [ "RunLengthEncoder", "classtdc_1_1_run_length_encoder.html", "classtdc_1_1_run_length_encoder" ],
    [ "RunRichGenerator", "classtdc_1_1_run_rich_generator.html", "classtdc_1_1_run_rich_generator" ],
    [ "SADivSufSort", "classtdc_1_1_s_a_div_suf_sort.html", "classtdc_1_1_s_a_div_suf_sort" ],
    [ "Select", "classtdc_1_1_select.html", "classtdc_1_1_select" ],
    [ "SizeManager", "classtdc_1_1_size_manager.html", "classtdc_1_1_size_manager" ],
    [ "SizeManagerDirect", "structtdc_1_1_size_manager_direct.html", "structtdc_1_1_size_manager_direct" ],
    [ "SizeManagerNoob", "structtdc_1_1_size_manager_noob.html", "structtdc_1_1_size_manager_noob" ],
    [ "SizeManagerPow2", "structtdc_1_1_size_manager_pow2.html", "structtdc_1_1_size_manager_pow2" ],
    [ "SizeManagerPrime", "structtdc_1_1_size_manager_prime.html", "structtdc_1_1_size_manager_prime" ],
    [ "SLECoder", "classtdc_1_1_s_l_e_coder.html", "classtdc_1_1_s_l_e_coder" ],
    [ "SparseISA", "classtdc_1_1_sparse_i_s_a.html", "classtdc_1_1_sparse_i_s_a" ],
    [ "StatPhase", "classtdc_1_1_stat_phase.html", "classtdc_1_1_stat_phase" ],
    [ "SuffixTree", "classtdc_1_1_suffix_tree.html", "classtdc_1_1_suffix_tree" ],
    [ "TernaryCoder", "classtdc_1_1_ternary_coder.html", "classtdc_1_1_ternary_coder" ],
    [ "TextDS", "classtdc_1_1_text_d_s.html", "classtdc_1_1_text_d_s" ],
    [ "ThueMorseGenerator", "classtdc_1_1_thue_morse_generator.html", "classtdc_1_1_thue_morse_generator" ],
    [ "TypeRange", "classtdc_1_1_type_range.html", "classtdc_1_1_type_range" ],
    [ "uint_dispatch_t", "structtdc_1_1uint__dispatch__t.html", "structtdc_1_1uint__dispatch__t" ],
    [ "uint_dispatch_t< 1 >", "structtdc_1_1uint__dispatch__t_3_011_01_4.html", "structtdc_1_1uint__dispatch__t_3_011_01_4" ],
    [ "uint_impl_t", "classtdc_1_1uint__impl__t.html", "classtdc_1_1uint__impl__t" ],
    [ "uint_impl_t< 1 >", "classtdc_1_1uint__impl__t_3_011_01_4.html", null ],
    [ "UinttDispatch", "structtdc_1_1_uintt_dispatch.html", "structtdc_1_1_uintt_dispatch" ],
    [ "ViewLiterals", "classtdc_1_1_view_literals.html", "classtdc_1_1_view_literals" ],
    [ "VignaHasher", "structtdc_1_1_vigna_hasher.html", "structtdc_1_1_vigna_hasher" ],
    [ "WordpackRollingHash", "classtdc_1_1_wordpack_rolling_hash.html", "classtdc_1_1_wordpack_rolling_hash" ],
    [ "ZBackupRollingHash", "classtdc_1_1_z_backup_rolling_hash.html", "classtdc_1_1_z_backup_rolling_hash" ]
];