var namespacetdc =
[
    [ "ds", "namespacetdc_1_1ds.html", "namespacetdc_1_1ds" ],
    [ "huff", "namespacetdc_1_1huff.html", "namespacetdc_1_1huff" ],
    [ "int_vector", "namespacetdc_1_1int__vector.html", "namespacetdc_1_1int__vector" ],
    [ "io", "namespacetdc_1_1io.html", "namespacetdc_1_1io" ],
    [ "json", "namespacetdc_1_1json.html", "namespacetdc_1_1json" ],
    [ "lcpcomp", "namespacetdc_1_1lcpcomp.html", "namespacetdc_1_1lcpcomp" ],
    [ "libdivsufsort", "namespacetdc_1_1libdivsufsort.html", "namespacetdc_1_1libdivsufsort" ],
    [ "lz78", "namespacetdc_1_1lz78.html", "namespacetdc_1_1lz78" ],
    [ "lz78u", "namespacetdc_1_1lz78u.html", "namespacetdc_1_1lz78u" ],
    [ "lzss", "namespacetdc_1_1lzss.html", "namespacetdc_1_1lzss" ],
    [ "_DoubleHashingProber", "structtdc_1_1___double_hashing_prober.html", null ],
    [ "Algorithm", "classtdc_1_1_algorithm.html", "classtdc_1_1_algorithm" ],
    [ "AlgorithmValue", "classtdc_1_1_algorithm_value.html", "classtdc_1_1_algorithm_value" ],
    [ "ArrayDS", "classtdc_1_1_array_d_s.html", "classtdc_1_1_array_d_s" ],
    [ "ArrayMaxHeap", "classtdc_1_1_array_max_heap.html", "classtdc_1_1_array_max_heap" ],
    [ "ASCIICoder", "classtdc_1_1_a_s_c_i_i_coder.html", "classtdc_1_1_a_s_c_i_i_coder" ],
    [ "BitCoder", "classtdc_1_1_bit_coder.html", "classtdc_1_1_bit_coder" ],
    [ "Builder", "classtdc_1_1_builder.html", "classtdc_1_1_builder" ],
    [ "BWTCompressor", "classtdc_1_1_b_w_t_compressor.html", "classtdc_1_1_b_w_t_compressor" ],
    [ "ChainCompressor", "classtdc_1_1_chain_compressor.html", "classtdc_1_1_chain_compressor" ],
    [ "Compressor", "classtdc_1_1_compressor.html", "classtdc_1_1_compressor" ],
    [ "ConstGenericView", "classtdc_1_1_const_generic_view.html", "classtdc_1_1_const_generic_view" ],
    [ "ConstGenericView< uliteral_t >", "classtdc_1_1_const_generic_view_3_01uliteral__t_01_4.html", "classtdc_1_1_const_generic_view_3_01uliteral__t_01_4" ],
    [ "ConstIntegerBaseCombiner", "classtdc_1_1_const_integer_base_combiner.html", null ],
    [ "ConstIntegerBaseCombiner< T >", "classtdc_1_1_const_integer_base_combiner_3_01_t_01_4.html", null ],
    [ "ConstIntegerBaseCombiner< T, Ts... >", "classtdc_1_1_const_integer_base_combiner_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
    [ "ConstIntegerBaseTrait", "structtdc_1_1_const_integer_base_trait.html", [
      [ "type", "structtdc_1_1_const_integer_base_trait_1_1type.html", "structtdc_1_1_const_integer_base_trait_1_1type" ]
    ] ],
    [ "ConstIntegerBaseTrait< dynamic_t >", "structtdc_1_1_const_integer_base_trait_3_01dynamic__t_01_4.html", "structtdc_1_1_const_integer_base_trait_3_01dynamic__t_01_4" ],
    [ "ConstIntegerBaseTrait< int_vector::ConstIntRef< dynamic_t > >", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_const_int_ref_3_01dynamic__t_01_4_01_4.html", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_const_int_ref_3_01dynamic__t_01_4_01_4" ],
    [ "ConstIntegerBaseTrait< int_vector::IntRef< dynamic_t > >", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_int_ref_3_01dynamic__t_01_4_01_4.html", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_int_ref_3_01dynamic__t_01_4_01_4" ],
    [ "ConstIntegerBaseWith32", "classtdc_1_1_const_integer_base_with32.html", "classtdc_1_1_const_integer_base_with32" ],
    [ "ConstIntegerBaseWith64", "classtdc_1_1_const_integer_base_with64.html", "classtdc_1_1_const_integer_base_with64" ],
    [ "ConstIntegerBaseWithSelf", "classtdc_1_1_const_integer_base_with_self.html", "classtdc_1_1_const_integer_base_with_self" ],
    [ "Counter", "classtdc_1_1_counter.html", "classtdc_1_1_counter" ],
    [ "Decoder", "classtdc_1_1_decoder.html", "classtdc_1_1_decoder" ],
    [ "DoubleHashingProber", "classtdc_1_1_double_hashing_prober.html", "classtdc_1_1_double_hashing_prober" ],
    [ "dynamic_t", "classtdc_1_1dynamic__t.html", "classtdc_1_1dynamic__t" ],
    [ "DyntDispatch", "structtdc_1_1_dynt_dispatch.html", "structtdc_1_1_dynt_dispatch" ],
    [ "EliasDeltaCoder", "classtdc_1_1_elias_delta_coder.html", "classtdc_1_1_elias_delta_coder" ],
    [ "EliasGammaCoder", "classtdc_1_1_elias_gamma_coder.html", "classtdc_1_1_elias_gamma_coder" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_int_ref_3_01uint__t_3_01_n_01_4_01_4_14a76d8821f8d9ae8e37a3d831c166c1.html", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_int_ref_3_01uint__t_3_01_n_01_4_01_4_14a76d8821f8d9ae8e37a3d831c166c1" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_integer_base_trait_3_01int__vector_1_1_int_ref_3_01uint__t_3_01_n_01_4_01_4_00_01taa2794a6825e1ee94ecb0ac2b8d96652.html", "structtdc_1_1_integer_base_trait_3_01int__vector_1_1_int_ref_3_01uint__t_3_01_n_01_4_01_4_00_01taa2794a6825e1ee94ecb0ac2b8d96652" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_const_int_ref_3_01uint__t_3_01_n_01_40551722f2b242ac7eb00c71c10bc7e01.html", "structtdc_1_1_const_integer_base_trait_3_01int__vector_1_1_const_int_ref_3_01uint__t_3_01_n_01_40551722f2b242ac7eb00c71c10bc7e01" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_const_integer_base_trait_3_01uint__t_3_01_n_01_4_00_01typename_01std_1_1enable__if98931aa7cbfcd97f62e54965a157a76a.html", "structtdc_1_1_const_integer_base_trait_3_01uint__t_3_01_n_01_4_00_01typename_01std_1_1enable__if98931aa7cbfcd97f62e54965a157a76a" ],
    [ "enable_if<(N<=32)>::type >", "structtdc_1_1_integer_base_trait_3_01uint__t_3_01_n_01_4_00_01typename_01std_1_1enable__if_3_07_n_3_0A32_08_4_1_1type_01_4.html", "structtdc_1_1_integer_base_trait_3_01uint__t_3_01_n_01_4_00_01typename_01std_1_1enable__if_3_07_n_3_0A32_08_4_1_1type_01_4" ],
    [ "Encoder", "classtdc_1_1_encoder.html", "classtdc_1_1_encoder" ],
    [ "Env", "classtdc_1_1_env.html", "classtdc_1_1_env" ],
    [ "EnvRoot", "classtdc_1_1_env_root.html", "classtdc_1_1_env_root" ],
    [ "FibonacciGenerator", "classtdc_1_1_fibonacci_generator.html", "classtdc_1_1_fibonacci_generator" ],
    [ "FixedRange", "classtdc_1_1_fixed_range.html", "classtdc_1_1_fixed_range" ],
    [ "GaussProber", "classtdc_1_1_gauss_prober.html", null ],
    [ "Generator", "classtdc_1_1_generator.html", "classtdc_1_1_generator" ],
    [ "GenericView", "classtdc_1_1_generic_view.html", "classtdc_1_1_generic_view" ],
    [ "GenericViewBase", "classtdc_1_1_generic_view_base.html", "classtdc_1_1_generic_view_base" ],
    [ "HuffmanCoder", "classtdc_1_1_huffman_coder.html", "classtdc_1_1_huffman_coder" ],
    [ "IntegerBaseCombiner", "classtdc_1_1_integer_base_combiner.html", null ],
    [ "IntegerBaseCombiner< T >", "classtdc_1_1_integer_base_combiner_3_01_t_01_4.html", null ],
    [ "IntegerBaseCombiner< T, Ts... >", "classtdc_1_1_integer_base_combiner_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
    [ "IntegerBaseTrait", "structtdc_1_1_integer_base_trait.html", [
      [ "type", "structtdc_1_1_integer_base_trait_1_1type.html", "structtdc_1_1_integer_base_trait_1_1type" ]
    ] ],
    [ "IntegerBaseTrait< dynamic_t >", "structtdc_1_1_integer_base_trait_3_01dynamic__t_01_4.html", "structtdc_1_1_integer_base_trait_3_01dynamic__t_01_4" ],
    [ "IntegerBaseTrait< int_vector::IntRef< dynamic_t > >", "structtdc_1_1_integer_base_trait_3_01int__vector_1_1_int_ref_3_01dynamic__t_01_4_01_4.html", "structtdc_1_1_integer_base_trait_3_01int__vector_1_1_int_ref_3_01dynamic__t_01_4_01_4" ],
    [ "IntegerBaseWith32", "classtdc_1_1_integer_base_with32.html", "classtdc_1_1_integer_base_with32" ],
    [ "IntegerBaseWith64", "classtdc_1_1_integer_base_with64.html", "classtdc_1_1_integer_base_with64" ],
    [ "IntegerBaseWithSelf", "classtdc_1_1_integer_base_with_self.html", "classtdc_1_1_integer_base_with_self" ],
    [ "ISAFromSA", "classtdc_1_1_i_s_a_from_s_a.html", "classtdc_1_1_i_s_a_from_s_a" ],
    [ "LCPCompressor", "classtdc_1_1_l_c_p_compressor.html", "classtdc_1_1_l_c_p_compressor" ],
    [ "LCPForwardIterator", "classtdc_1_1_l_c_p_forward_iterator.html", "classtdc_1_1_l_c_p_forward_iterator" ],
    [ "LCPFromPLCP", "classtdc_1_1_l_c_p_from_p_l_c_p.html", "classtdc_1_1_l_c_p_from_p_l_c_p" ],
    [ "LCPSada", "classtdc_1_1_l_c_p_sada.html", "classtdc_1_1_l_c_p_sada" ],
    [ "LengthRange", "classtdc_1_1_length_range.html", "classtdc_1_1_length_range" ],
    [ "LinearProber", "classtdc_1_1_linear_prober.html", null ],
    [ "Literal", "structtdc_1_1_literal.html", "structtdc_1_1_literal" ],
    [ "LiteralEncoder", "classtdc_1_1_literal_encoder.html", "classtdc_1_1_literal_encoder" ],
    [ "LiteralIterator", "classtdc_1_1_literal_iterator.html", "classtdc_1_1_literal_iterator" ],
    [ "LiteralRange", "classtdc_1_1_literal_range.html", "classtdc_1_1_literal_range" ],
    [ "LZ78Compressor", "classtdc_1_1_l_z78_compressor.html", "classtdc_1_1_l_z78_compressor" ],
    [ "LZ78UCompressor", "classtdc_1_1_l_z78_u_compressor.html", "classtdc_1_1_l_z78_u_compressor" ],
    [ "LZSSLCPCompressor", "classtdc_1_1_l_z_s_s_l_c_p_compressor.html", "classtdc_1_1_l_z_s_s_l_c_p_compressor" ],
    [ "LZSSSlidingWindowCompressor", "classtdc_1_1_l_z_s_s_sliding_window_compressor.html", "classtdc_1_1_l_z_s_s_sliding_window_compressor" ],
    [ "LZWCompressor", "classtdc_1_1_l_z_w_compressor.html", "classtdc_1_1_l_z_w_compressor" ],
    [ "Meta", "classtdc_1_1_meta.html", "classtdc_1_1_meta" ],
    [ "MinDistributedRange", "classtdc_1_1_min_distributed_range.html", "classtdc_1_1_min_distributed_range" ],
    [ "MixHasher", "classtdc_1_1_mix_hasher.html", "classtdc_1_1_mix_hasher" ],
    [ "MTFCompressor", "classtdc_1_1_m_t_f_compressor.html", "classtdc_1_1_m_t_f_compressor" ],
    [ "NoLiterals", "classtdc_1_1_no_literals.html", null ],
    [ "NoopCompressor", "classtdc_1_1_noop_compressor.html", "classtdc_1_1_noop_compressor" ],
    [ "OptionValue", "classtdc_1_1_option_value.html", "classtdc_1_1_option_value" ],
    [ "PhiFromSA", "classtdc_1_1_phi_from_s_a.html", "classtdc_1_1_phi_from_s_a" ],
    [ "PLCPFromPhi", "classtdc_1_1_p_l_c_p_from_phi.html", "classtdc_1_1_p_l_c_p_from_phi" ],
    [ "QuadraticProber", "classtdc_1_1_quadratic_prober.html", null ],
    [ "RandomUniformGenerator", "classtdc_1_1_random_uniform_generator.html", "classtdc_1_1_random_uniform_generator" ],
    [ "Range", "classtdc_1_1_range.html", "classtdc_1_1_range" ],
    [ "RefDispatch", "structtdc_1_1_ref_dispatch.html", "structtdc_1_1_ref_dispatch" ],
    [ "Registry", "classtdc_1_1_registry.html", "classtdc_1_1_registry" ],
    [ "RePairCompressor", "classtdc_1_1_re_pair_compressor.html", "classtdc_1_1_re_pair_compressor" ],
    [ "RunLengthEncoder", "classtdc_1_1_run_length_encoder.html", "classtdc_1_1_run_length_encoder" ],
    [ "RunRichGenerator", "classtdc_1_1_run_rich_generator.html", "classtdc_1_1_run_rich_generator" ],
    [ "SADivSufSort", "classtdc_1_1_s_a_div_suf_sort.html", "classtdc_1_1_s_a_div_suf_sort" ],
    [ "SizeManagerPow2", "structtdc_1_1_size_manager_pow2.html", null ],
    [ "SLECoder", "classtdc_1_1_s_l_e_coder.html", "classtdc_1_1_s_l_e_coder" ],
    [ "StatPhase", "classtdc_1_1_stat_phase.html", "classtdc_1_1_stat_phase" ],
    [ "TernaryCoder", "classtdc_1_1_ternary_coder.html", "classtdc_1_1_ternary_coder" ],
    [ "TextDS", "classtdc_1_1_text_d_s.html", "classtdc_1_1_text_d_s" ],
    [ "ThueMorseGenerator", "classtdc_1_1_thue_morse_generator.html", "classtdc_1_1_thue_morse_generator" ],
    [ "TypeRange", "classtdc_1_1_type_range.html", "classtdc_1_1_type_range" ],
    [ "uint_t", "classtdc_1_1uint__t.html", "classtdc_1_1uint__t" ],
    [ "UinttDispatch", "structtdc_1_1_uintt_dispatch.html", "structtdc_1_1_uintt_dispatch" ],
    [ "ViewLiterals", "classtdc_1_1_view_literals.html", "classtdc_1_1_view_literals" ]
];